version: '3'

services:
  nodestore:
    container_name: nodestore
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api:/src/api"
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_SERVER=mongostore
      - MONGO_DB=store
      - MONGO_PORT=27017
    depends_on: [ mongostore ]
  mongoseed:
    container_name: mongoseed
    build: ./mongoseed
    depends_on: [ mongostore ]
  mongostore:
    container_name: mongostore
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - ./data/db:/data/db
  reactstore:
    container_name: reactstore
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/src"
    ports:
      - "3000:3000"
    depends_on: [ nodestore ]